apiVersion: apps/v1
kind: Deployment
metadata:
  name: options-cache-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: options-cache
  template:
    metadata:
      labels:
        app: options-cache
    spec:
      containers:
      - name: options-cache
        image: artifacts.tekuro.io/cache:229fada6c7f9a6a900fde0bf1280c4f18535775e
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST  
          value: redis-master.redis.svc.cluster.local  # Full Redis service DNS
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD  # Adding Redis password from the secret
          valueFrom:
            secretKeyRef:
              name: redis  # The name of the secret
              key: REDIS_PASSWORD  # The key within the secret
              optional: false
      imagePullSecrets:
        - name: regcred  # For pulling the image from a private registry
