apiVersion: apps/v1
kind: Deployment
metadata:
  name: options-cache-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: options-cache
  template:
    metadata:
      labels:
        app: options-cache
    spec:
      containers:
      - name: options-cache
        image: artifacts.tekuro.io/cache:22ea042535e06ca8418aafd35906d5ab4b200379
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST  
          value: redis-master.redis.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
      imagePullSecrets:
        - name: regcred